class ApplicationException(Exception):
    def __init__(self, message):
        self.message = message

class GetJobException(ApplicationException): ...
    
class GetJobListingException(ApplicationException): ...

class SourceParsingError(ApplicationException): ...

class JobNotFound(ApplicationException): ...